<!DOCTYPE html>
	<head>
		<meta charset="utf-8" />
	   <title>Deep Work_</title>
	   <link REL="shortcut icon" href="images/icone.png">
	   <link rel="stylesheet" media="screen" type="text/css" title="Style" href="style/styles.css" />
	</head>
   
   <body Style="width:1700px; text-align:center;">

<h1 Style="text-align:center;">Deep Work</h1>
<h2 Style="text-align:center;">Compteur d'heures d'apprentissage : Freelance...</h2>

	<ul style="-moz-column-count: 5; -moz-column-gap: 20px; -webkit-column-count: 5; -webkit-column-gap: 20px; column-count: 5; column-gap: 20px;">
		<li>Jour 001 - 25022019 - 7h</li> <?php $jour1 = 7;?>
		<li>Jour 002 - 26022019 - 7h</li> <?php $jour2 = 7;?>
		<li>Jour 003 - 27022019 - 6h</li> <?php $jour3 = 6;?>
		<li>Jour 004 - 28022019 - 3h</li> <?php $jour4 = 3;?>
		<li>Jour 005 - 01032019 - 1h</li> <?php $jour5 = 1;?>
		<li>Jour 006 - 02032019 - 1h</li> <?php $jour6 = 1;?>
		<li>Jour 007 - 03032019 - 2h</li> <?php $jour7 = 2;?>
		<li>Jour 008 - 05032019 - 6h</li> <?php $jour8 = 6;?>
		<li>Jour 009 - 06032019 - 2h</li> <?php $jour9 = 2;?>
		<li>Jour 010 - 07032019 - 4h</li> <?php $jour10 = 4;?>
		<li>Jour 011 - 08032019 - 2h</li> <?php $jour11 = 2;?>
		<li>Jour 012 - 11032019 - 5h</li> <?php $jour12 = 5;?>
		<li>Jour 013 - 22092019 - 5h</li> <?php $jour13 = 5;?>
		<li>Jour 014 - 23092019 - 4h</li> <?php $jour14 = 4;?>
		<li>Jour 015 - 26022020 - 4h</li> <?php $jour15 = 4;?>
		<li>Jour 016 - 29022020 - 2h</li> <?php $jour16 = 2;?>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
		<li>Jour xxx - yyyyyyyy - zh</li>
	</ul>

	<?php $total = $jour1 + $jour2 + $jour3 + $jour4 + $jour5 + $jour6 + $jour7 + $jour8 + $jour9 + $jour10 + $jour11 + $jour12 + $jour13 + $jour14 + $jour15 + $jour16; ?>
	<p Style="text-align:center;"><strong>Total :</strong> <?php echo $total; ?>/8000 <strong>soit</strong> <?php echo $total*100/8000?>%</p>

<h3 Style="text-align:center;">Compétences</h3>

	<div Style="text-align:center;">
		<p>
			<img src="images/logos/Angular.png" Style="opacity: 0.5;">
			<img src="images/logos/powershell.png" Style="opacity: 0.5;">
			<img src="images/logos/C.png" Style="opacity: 0.5;">
			<img src="images/logos/CPP.png" Style="opacity: 0.5;">
			<img src="images/logos/python3.png" Style="opacity: 0.5;">
			<img src="images/logos/html5.png">
			<img src="images/logos/css3.png">
			<img src="images/logos/php.png">
			<img src="images/logos/MySQL.png">
			<img src="images/logos/github.png" Style="opacity: 0.5;">
			<img src="images/logos/Java.png" Style="opacity: 0.5;">
			<img src="images/logos/Javascript.png" Style="opacity: 0.5;">
			<img src="images/logos/Ruby.png" Style="opacity: 0.5;">
			<img src="images/logos/Ruby_On_Rails.png" Style="opacity: 0.5;">
			<img src="images/logos/blender.png" Style="opacity: 0.5;">
			<img src="images/logos/unity.png" Style="opacity: 0.5;">
		</p>
	<div>

	<div Style="margin:auto; width:600px; height:800px;">
		<p Style="text-align:center;"><strong>Angular</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Powershell</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Unity</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Blender</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>C++</strong> 24% <br><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>HTML & CSS 3 :</strong> 100% <br><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Java</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Javascript</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>PHP & MySQL</strong> 100% <br><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Github</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Python</strong> 0% <br><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Ruby</strong> 12% <br><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
		<p Style="text-align:center;"><strong>Ruby on Rails</strong> 3% <br><img src="images/progress_green.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"><img src="images/progress_grey.png"  width="15px" height="20px"></p>
	</div>
   </body>
   
</html>
